name: Security vulnerabilities check
on: push
jobs:
  security-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Software Composition Analysis using Snyk
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        continue-on-error: false
      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: my-report
          path: synk-scan-report.txt
      
